debug: false
mode: client # client, server
api: example.com
token: 00000000-0000-0000-0000-000000000000
node: 1 # server 配置
stack: default # ipv4, ipv6, default client配置
scheduler: "0 30 */3 * * *"
exclude: []